/* GENERATED by scripts/extract-skin.mjs — do not edit by hand.
 * Measured from the DOM binding wearing the example skin, at 1440×900, DPR 1.
 * Coordinates are relative to the ribbon plate's top-left corner.
 */
export const SKIN = {
  "plate": {
    "w": 840,
    "h": 90,
    "x": 0,
    "y": 0,
    "bg": "rgba(0, 0, 0, 0.6)",
    "color": "rgb(0, 0, 0)",
    "radius": 2,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(0, 0, 0)"
    },
    "shadow": "rgba(0, 0, 0, 0.3) 0px 3px 5px 3px",
    "text": "BUY BONUSSOUNDMUSICSUPER TURBOBASE GAMEB"
  },
  "UiWrapper": {
    "x": 0,
    "y": 0,
    "w": 840,
    "h": 110.39,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(0, 0, 0)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(0, 0, 0)"
    },
    "shadow": null,
    "text": "BUY BONUSSOUNDMUSICSUPER TURBOBASE GAMEB"
  },
  "MainPanel": {
    "x": 4.8,
    "y": 10,
    "w": 830.41,
    "h": 70,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": "BUY BONUSSOUNDMUSICSUPER TURBOBASE GAMEB"
  },
  "DataPanel": {
    "x": 4.8,
    "y": 10,
    "w": 481.72,
    "h": 70,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": "SOUNDMUSICSUPER TURBOBASE GAMEBONUS GAME"
  },
  "ActionPanel": {
    "x": 486.52,
    "y": 10,
    "w": 348.69,
    "h": 70,
    "bg": "rgb(38, 38, 38)",
    "color": "rgb(250, 250, 250)",
    "radius": 3,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 3,
      "color": "rgb(13, 13, 13)"
    },
    "shadow": null,
    "text": "BET$1.000"
  },
  "FeatureBuyToggle": {
    "x": -118.2,
    "y": -14.4,
    "w": 118.79,
    "h": 118.79,
    "bg": "rgb(255, 198, 55)",
    "color": "rgb(0, 0, 0)",
    "radius": 100,
    "font": {
      "size": 14,
      "weight": "700",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "capitalize"
    },
    "border": {
      "width": 0,
      "color": "rgb(0, 0, 0)"
    },
    "shadow": null,
    "text": "BUY BONUS"
  },
  "MainMenuToggle": {
    "x": 5.8,
    "y": 17,
    "w": 55,
    "h": 56,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 26,
      "weight": "500",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "capitalize"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": ""
  },
  "BalanceItem": {
    "x": 73.3,
    "y": 26.39,
    "w": 113.7,
    "h": 37.22,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": "BALANCE$12,345.67"
  },
  "BalanceLabel": {
    "x": 81.3,
    "y": 26.39,
    "w": 65.36,
    "h": 16.09,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(255, 255, 255)",
    "radius": 0,
    "font": {
      "size": 14,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(255, 255, 255)"
    },
    "shadow": null,
    "text": "BALANCE"
  },
  "BalanceValue": {
    "x": 81.3,
    "y": 42.48,
    "w": 105.7,
    "h": 21.13,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(255, 255, 255)",
    "radius": 0,
    "font": {
      "size": 21.12,
      "weight": "700",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(255, 255, 255)"
    },
    "shadow": null,
    "text": "$12,345.67"
  },
  "WinAmountItem": {
    "x": 203,
    "y": 24.95,
    "w": 60.06,
    "h": 40.09,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": "WIN$0.00"
  },
  "WinAmountLabel": {
    "x": 203,
    "y": 24.95,
    "w": 27.22,
    "h": 16.09,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(255, 255, 255)",
    "radius": 0,
    "font": {
      "size": 14,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(255, 255, 255)"
    },
    "shadow": null,
    "text": "WIN"
  },
  "WinAmountValue": {
    "x": 203,
    "y": 41.05,
    "w": 60.06,
    "h": 24,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(255, 255, 255)",
    "radius": 0,
    "font": {
      "size": 24,
      "weight": "700",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(255, 255, 255)"
    },
    "shadow": null,
    "text": "$0.00"
  },
  "BetAmountItem": {
    "x": 489.52,
    "y": 13,
    "w": 120,
    "h": 64,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": "BET$1.00"
  },
  "BetAmountLabel": {
    "x": 504.52,
    "y": 24.95,
    "w": 60.06,
    "h": 16.09,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(255, 255, 255)",
    "radius": 0,
    "font": {
      "size": 14,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(255, 255, 255)"
    },
    "shadow": null,
    "text": "BET"
  },
  "BetAmountValue": {
    "x": 504.52,
    "y": 41.05,
    "w": 60.06,
    "h": 24,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(255, 255, 255)",
    "radius": 0,
    "font": {
      "size": 24,
      "weight": "700",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(255, 255, 255)"
    },
    "shadow": null,
    "text": "$1.00"
  },
  "BetAmountIndicatorProgress": {
    "x": 489.52,
    "y": 72,
    "w": 48,
    "h": 5,
    "bg": "rgb(255, 255, 255)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": ""
  },
  "BetAmountIncrease": {
    "x": 611.09,
    "y": 13,
    "w": 49.02,
    "h": 32,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 4,
    "font": {
      "size": 12,
      "weight": "500",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "capitalize"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": ""
  },
  "BetAmountDecrease": {
    "x": 611.02,
    "y": 45,
    "w": 49.19,
    "h": 32,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 4,
    "font": {
      "size": 12,
      "weight": "500",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "capitalize"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": ""
  },
  "PlaceBetBtn": {
    "x": 660.2,
    "y": -11,
    "w": 112,
    "h": 112,
    "bg": "rgb(38, 38, 38)",
    "color": "rgb(250, 250, 250)",
    "radius": 100,
    "font": {
      "size": 86.4,
      "weight": "500",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "capitalize"
    },
    "border": {
      "width": 3,
      "color": "rgb(0, 0, 0)"
    },
    "shadow": null,
    "text": ""
  },
  "AutoplayBtn": {
    "x": 772.2,
    "y": 15,
    "w": 60,
    "h": 60,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 100,
    "font": {
      "size": 34,
      "weight": "500",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "capitalize"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": ""
  },
  "FeedbackMsg": {
    "x": 0,
    "y": -30,
    "w": 840,
    "h": 20,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(255, 255, 255)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "700",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(255, 255, 255)"
    },
    "shadow": null,
    "text": "PRESS PLAY TO SPIN!"
  },
  "BetAmountProgressbar": {
    "x": 489.52,
    "y": 72,
    "w": 120,
    "h": 5,
    "bg": "rgba(0, 0, 0, 0.9)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": ""
  },
  "divider": {
    "x": 66.8,
    "y": 0,
    "w": 0.5,
    "h": 90,
    "bg": "rgb(173, 181, 189)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": ""
  },
  "coinContainer": {
    "x": -100.8,
    "y": 3,
    "w": 84,
    "h": 84,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": "BUY BONUS"
  },
  "BetAmountWidget": {
    "x": 504.52,
    "y": 24.95,
    "w": 60.06,
    "h": 40.09,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": "BET$1.00"
  },
  "coin": {
    "size": 84,
    "rotation": -0.7854,
    "padding": 6,
    "lineHeight": 14,
    "ring": {
      "width": 3,
      "color": "rgb(0, 0, 0)",
      "size": 80,
      "inset": 2
    }
  },
  "BetAmountChangers": {
    "x": 610.02,
    "y": 13,
    "w": 50.19,
    "h": 64,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": ""
  },
  "actions": {
    "x": 610.02,
    "y": 13,
    "w": 162.19,
    "h": 64,
    "bg": "rgba(0, 0, 0, 0)",
    "color": "rgb(250, 250, 250)",
    "radius": 0,
    "font": {
      "size": 16,
      "weight": "400",
      "family": "HacksawUI",
      "spacing": "normal",
      "transform": "none"
    },
    "border": {
      "width": 0,
      "color": "rgb(250, 250, 250)"
    },
    "shadow": null,
    "text": "0"
  },
  "glyphs": {
    "menu": {
      "content": "\"\"",
      "font": "icomoon",
      "size": 26,
      "color": "rgb(250, 250, 250)"
    },
    "spin": {
      "content": "\"\"",
      "font": "icomoon",
      "size": 86.4,
      "color": "rgb(250, 250, 250)"
    },
    "autoplay": {
      "content": "\"\"",
      "font": "icomoon",
      "size": 34,
      "color": "rgb(250, 250, 250)"
    },
    "up": {
      "content": "\"\"",
      "font": "icomoon",
      "size": 22,
      "color": "rgb(250, 250, 250)"
    },
    "down": {
      "content": "\"\"",
      "font": "icomoon",
      "size": 22,
      "color": "rgb(250, 250, 250)"
    },
    "stop": {
      "content": "\"\"",
      "font": "icomoon",
      "size": 52,
      "color": "rgb(250, 250, 250)"
    }
  },
  "viewport": {
    "w": 1440,
    "h": 900
  },
  "anchor": {
    "bottomGap": 20.39
  },
  "page": {
    "background": "rgb(13, 13, 13)"
  }
} as const;

export type SkinManifest = typeof SKIN;
